// Generated by CoffeeScript 1.9.1
(function() {
  var Doctor, con, eapp, express, mongoose, server;

  express = require('express');

  mongoose = require('mongoose');

  Doctor = require('./models/Doctor');

  mongoose.connect('mongodb://dbuser:dbpassword@ds045001.mongolab.com:45001/medify4');

  con = mongoose.connection;

  con.once('open', function(err, data) {
    return console.log("Connected to remote mongoDB");
  });

  eapp = express();

  eapp.use(express["static"](__dirname + '/public')).set('views', __dirname).set('view engine', 'jade').get('/api/doctors', function(req, res) {
    return mongoose.model('Doctor').find({}).exec(function(err, collection) {
      console.log(collection);
      return res.send(collection);
    });
  }).get('*', function(req, res) {
    return res.render('index');
  });

  server = eapp.listen(process.env.PORT || 9000, process.env.IP || '127.0.0.1', function() {
    var host, port, protocol;
    host = server.address().address;
    port = server.address().port;
    protocol = server.address().family;
    return console.log("Server listening at http://%s:%s (protocol %s)", host, port, protocol);
  });

}).call(this);
